"""add is_admin column to users

Revision ID: 27978a966caf
Revises: 84c969d15e87
Create Date: 2026-05-15 14:43:52.162370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27978a966caf'
down_revision = '84c969d15e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
