"""Added soft delete to messages

Revision ID: 38b51009fb99
Revises: 0dd2c1dd1502
Create Date: 2026-03-29 16:56:35.533539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b51009fb99'
down_revision = '0dd2c1dd1502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_recipient', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_recipient')
        batch_op.drop_column('deleted_by_sender')

    # ### end Alembic commands ###
